/**
 * A sixty-day Achilles course — the first test material in this engine that
 * was not written by the person who set the thresholds.
 *
 * ---------------------------------------------------------------------------
 * WHAT THIS IS, AND WHAT IT IS NOT.
 *
 * Generated by a language model to a realistic shape, then handed over. It is
 * therefore NOT lived data and not independent clinical evidence — a model may
 * well encode the same intuitions the rules encode.
 *
 * What it is: a course with cross-training, a graded return to running, two
 * annotated reaction days, and a recovery from 6 out of 10 to 1. None of that
 * came out of a formula in fixtures.ts, which every other scenario here did.
 * That alone makes it the closest thing to an outside opinion this engine has,
 * and it is the reason it is checked in rather than run once and discarded.
 *
 * The diary's own notes flagged two days as reactions. The engine found the
 * same two without ever reading a note — free text never enters a rule.
 * ---------------------------------------------------------------------------
 */

import type { Entry } from "./types.js";

export const ACHILLES_60_DAYS: Entry[] = [
  { date: "2026-06-22", morningScore: 6, activityKind: "walk", durationMin: 30, rpe: 4, symptomScore: 4, symptomTiming: "during" },
  { date: "2026-06-23", morningScore: 5, activityKind: "cycle", durationMin: 35, rpe: 4, symptomScore: 2, symptomTiming: "after" },
  { date: "2026-06-24", morningScore: 4, activityKind: "strength_lower", durationMin: 25, rpe: 5, symptomScore: 3, symptomTiming: "during" },
  { date: "2026-06-25", morningScore: 4 },
  { date: "2026-06-26", morningScore: 3, activityKind: "swim", durationMin: 40, rpe: 5, symptomScore: 1, symptomTiming: "after" },
  { date: "2026-06-27", morningScore: 3, activityKind: "strength_upper", durationMin: 45, rpe: 6, symptomScore: 0, symptomTiming: "during" },
  { date: "2026-06-28", morningScore: 3, activityKind: "walk", durationMin: 40, rpe: 4, symptomScore: 3, symptomTiming: "evening" },
  { date: "2026-06-29", morningScore: 4 },
  { date: "2026-06-30", morningScore: 3, activityKind: "strength_lower", durationMin: 30, rpe: 5, symptomScore: 2, symptomTiming: "during" },
  { date: "2026-07-01", morningScore: 3, activityKind: "cycle", durationMin: 45, rpe: 5, symptomScore: 1, symptomTiming: "after" },
  { date: "2026-07-02", morningScore: 2 },
  { date: "2026-07-03", morningScore: 3, activityKind: "strength_lower", durationMin: 35, rpe: 6, symptomScore: 3, symptomTiming: "after" },
  { date: "2026-07-04", morningScore: 3, activityKind: "walk", durationMin: 45, rpe: 4, symptomScore: 2, symptomTiming: "during" },
  { date: "2026-07-05", morningScore: 2, activityKind: "swim", durationMin: 45, rpe: 5, symptomScore: 0, symptomTiming: "after" },
  { date: "2026-07-06", morningScore: 2, activityKind: "run", durationMin: 15, rpe: 5, symptomScore: 2, symptomTiming: "after" },
  { date: "2026-07-07", morningScore: 3 },
  { date: "2026-07-08", morningScore: 2, activityKind: "strength_lower", durationMin: 40, rpe: 6, symptomScore: 2, symptomTiming: "during" },
  { date: "2026-07-09", morningScore: 2, activityKind: "cycle", durationMin: 50, rpe: 6, symptomScore: 1, symptomTiming: "after" },
  { date: "2026-07-10", morningScore: 2, activityKind: "run", durationMin: 20, rpe: 6, symptomScore: 3, symptomTiming: "during" },
  { date: "2026-07-11", morningScore: 3, activityKind: "strength_upper", durationMin: 45, rpe: 5, symptomScore: 0, symptomTiming: "after" },
  { date: "2026-07-12", morningScore: 2 },
  { date: "2026-07-13", morningScore: 2, activityKind: "strength_lower", durationMin: 40, rpe: 7, symptomScore: 3, symptomTiming: "after" },
  { date: "2026-07-14", morningScore: 2, activityKind: "run", durationMin: 25, rpe: 6, symptomScore: 3, symptomTiming: "after" },
  { date: "2026-07-15", morningScore: 4 },
  { date: "2026-07-16", morningScore: 3, activityKind: "cycle", durationMin: 40, rpe: 4, symptomScore: 1, symptomTiming: "after" },
  { date: "2026-07-17", morningScore: 2, activityKind: "swim", durationMin: 45, rpe: 5, symptomScore: 0, symptomTiming: "after" },
  { date: "2026-07-18", morningScore: 2, activityKind: "strength_lower", durationMin: 35, rpe: 6, symptomScore: 2, symptomTiming: "during" },
  { date: "2026-07-19", morningScore: 2 },
  { date: "2026-07-20", morningScore: 2, activityKind: "run", durationMin: 25, rpe: 5, symptomScore: 2, symptomTiming: "after" },
  { date: "2026-07-21", morningScore: 2, activityKind: "strength_upper", durationMin: 45, rpe: 5, symptomScore: 0, symptomTiming: "during" },
  { date: "2026-07-22", morningScore: 1, activityKind: "hike", durationMin: 60, rpe: 5, symptomScore: 2, symptomTiming: "evening" },
  { date: "2026-07-23", morningScore: 2, activityKind: "strength_lower", durationMin: 45, rpe: 7, symptomScore: 2, symptomTiming: "during" },
  { date: "2026-07-24", morningScore: 1 },
  { date: "2026-07-25", morningScore: 1, activityKind: "run", durationMin: 30, rpe: 6, symptomScore: 2, symptomTiming: "after" },
  { date: "2026-07-26", morningScore: 2, activityKind: "cycle", durationMin: 60, rpe: 6, symptomScore: 1, symptomTiming: "after" },
  { date: "2026-07-27", morningScore: 1, activityKind: "strength_lower", durationMin: 40, rpe: 6, symptomScore: 1, symptomTiming: "during" },
  { date: "2026-07-28", morningScore: 2 },
  { date: "2026-07-29", morningScore: 1, activityKind: "run", durationMin: 35, rpe: 6, symptomScore: 2, symptomTiming: "after" },
  { date: "2026-07-30", morningScore: 1, activityKind: "swim", durationMin: 45, rpe: 5, symptomScore: 0, symptomTiming: "after" },
  { date: "2026-07-31", morningScore: 1, activityKind: "strength_lower", durationMin: 45, rpe: 7, symptomScore: 2, symptomTiming: "during" },
  { date: "2026-08-01", morningScore: 1, activityKind: "cycle", durationMin: 45, rpe: 5, symptomScore: 0, symptomTiming: "after" },
  { date: "2026-08-02", morningScore: 1 },
  { date: "2026-08-03", morningScore: 1, activityKind: "plyometric", durationMin: 20, rpe: 6, symptomScore: 3, symptomTiming: "during" },
  { date: "2026-08-04", morningScore: 2, activityKind: "strength_upper", durationMin: 50, rpe: 6, symptomScore: 0, symptomTiming: "after" },
  { date: "2026-08-05", morningScore: 1, activityKind: "run", durationMin: 40, rpe: 7, symptomScore: 2, symptomTiming: "after" },
  { date: "2026-08-06", morningScore: 1 },
  { date: "2026-08-07", morningScore: 1, activityKind: "strength_lower", durationMin: 45, rpe: 7, symptomScore: 1, symptomTiming: "during" },
  { date: "2026-08-08", morningScore: 1, activityKind: "run", durationMin: 35, rpe: 6, symptomScore: 1, symptomTiming: "after" },
  { date: "2026-08-09", morningScore: 1, activityKind: "cycle", durationMin: 50, rpe: 6, symptomScore: 0, symptomTiming: "after" },
  { date: "2026-08-10", morningScore: 1, activityKind: "plyometric", durationMin: 25, rpe: 7, symptomScore: 2, symptomTiming: "after" },
  { date: "2026-08-11", morningScore: 2, activityKind: "court_sport", durationMin: 45, rpe: 7, symptomScore: 3, symptomTiming: "evening" },
  { date: "2026-08-12", morningScore: 3 },
  { date: "2026-08-13", morningScore: 2, activityKind: "swim", durationMin: 40, rpe: 4, symptomScore: 0, symptomTiming: "after" },
  { date: "2026-08-14", morningScore: 1, activityKind: "strength_lower", durationMin: 40, rpe: 6, symptomScore: 1, symptomTiming: "during" },
  { date: "2026-08-15", morningScore: 1, activityKind: "run", durationMin: 45, rpe: 7, symptomScore: 1, symptomTiming: "after" },
  { date: "2026-08-16", morningScore: 1 },
  { date: "2026-08-17", morningScore: 0, activityKind: "cycle", durationMin: 60, rpe: 6, symptomScore: 0, symptomTiming: "after" },
  { date: "2026-08-18", morningScore: 0, activityKind: "strength_lower", durationMin: 45, rpe: 7, symptomScore: 1, symptomTiming: "during" },
  { date: "2026-08-19", morningScore: 1, activityKind: "run", durationMin: 50, rpe: 8, symptomScore: 1, symptomTiming: "after" },
  { date: "2026-08-20", morningScore: 1 },
];
